### ISSUE TITLE
Output data location

### ISSUE THREAD

**Issue by rwegener2** [pangeo-forge/noaa-coastwatch-geopolar-sst-feedstock#6]
I'm wondering if it's possible to get some information about where the data are located. I've been accessing data at the url: [https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/noaa-coastwatch-geopolar-sst-feedstock/noaa-coastwatch-geopolar-sst.zarr](https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/noaa-coastwatch-geopolar-sst-feedstock/noaa-coastwatch-geopolar-sst.zarr)
The data is in Google Cloud, correct? Is there a way for me to find out what region it is in?

Thanks so much for any information!

### Contextual information

For context, accessing data is slower than I expected. I have been running a chunk of code (below) to access a ~11.5MB chunk of data and it takes 13 minutes to load from my university’s server. The even more surprising thing is that it still takes 13 minutes to open from the GCP Pangeo Cloud server, where I expected data proximate computing to shine.

```
import xarray as xr

filepath = 'https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/noaa-coastwatch-geopolar-sst-feedstock/noaa-coastwatch-geopolar-sst.zarr'
geopolar = xr.open_zarr(filepath)
geopolar = geopolar.analysed_sst.sel(lat=slice(40, 41), lon=slice(-70, -69))
print(geopolar.nbytes / 1e6, 'MB')

sst_np = geopolar.values  # This is the line that takes 13+ minutes

```
To be really clear this is not at all a problem I expect anyone to solve - I can get this to be much faster with dask. The fact that 12MB takes so long even from GCP just made me want to double check that I understand where the data is located.

**Comment by cisaacstern** [comment]
@rwegener apologies for the delayed reply, I was somehow not subscribed to this repo, and didn't get the notification (I'm now watching it, so that shouldn't happen again).

Our OSN bucket is on AWS S3 (not GCS).

Regarding the region, I just ran

```console
aws s3api get-bucket-location --endpoint-url "https://ncsa.osn.xsede.org/" --bucket "Pangeo"
```

```
{
    "LocationConstraint": "default"
}
```
(This apparently requires credentials; not sure if/how to do it anonymously.)

And based on [this page](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html):

> [LocationConstraint](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CreateBucket.html#API_CreateBucket_RequestSyntax)
Specifies the Region where the bucket will be created. If you don't specify a Region, the bucket is created in the US East (N. Virginia) Region (us-east-1).

I interpret that to mean the OSN bucket is in AWS `us-east-1`.

So perhaps it's worth testing from the AWS Pangeo Cloud deployment, to see if the connection is any faster? I'll be interested to know if that improves throughput for you, because > 10 mins to load 12 MB of data seems _far_ too slow.

**Comment by rwegener2** [comment]
Thanks really helpful, thanks so much @cisaacstern!
